package com.school.app.controller;

import javafx.scene.control.ComboBox;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import java.util.stream.Collectors;

// Code generated by GEMINI. It was too difficult for me to deal
// with dynamic combobxes
public class FilterableComboBox {
  private final ComboBox<String> comboBox;
  private final ObservableList<String> originalList;
  private boolean isUpdating = false; // Flag specific to THIS ComboBox!

  public FilterableComboBox(ComboBox<String> comboBox, ObservableList<String> originalList) {
    this.comboBox = comboBox;
    this.originalList = originalList;
    this.comboBox.setItems(originalList);

    // Attach the listener, which calls the filter method on THIS instance.
    this.comboBox.getEditor().textProperty().addListener((observable, oldValue, newValue) -> {
      if (isUpdating) {
        return;
      }
      filterItems(newValue);
    });
  }

  private void filterItems(String filterText) {
    String input = filterText.trim().toLowerCase();
    ObservableList<String> itemsToSet = null;

    if (input.isEmpty()) {
      if (!comboBox.getItems().equals(originalList)) {
        itemsToSet = originalList;
      }
      comboBox.hide();
    } else {
      // Standard filtering logic
      ObservableList<String> filteredItems = originalList.stream()
          .filter(item -> item.toLowerCase().contains(input))
          .collect(Collectors.toCollection(FXCollections::observableArrayList));

      if (!comboBox.getItems().equals(filteredItems)) {
        itemsToSet = filteredItems;
      }
      if (!comboBox.isShowing()) {
        comboBox.show();
      }
    }

    // The synchronization block, now using the instance-specific 'isUpdating' flag
    if (itemsToSet != null) {
      try {
        isUpdating = true;
        comboBox.setItems(itemsToSet);
        comboBox.getEditor().setText(filterText);
      } finally {
        isUpdating = false;
        comboBox.getEditor().positionCaret(comboBox.getEditor().getText().length());
      }
    }
  }

  public ComboBox<String> getComboBox() {
    return this.comboBox;
  }

  public void setFilteredItems(ObservableList<String> filteredItems) {
    this.originalList.setAll(filteredItems);
  }

}
